INSERT INTO HARDWARE_CATEGORY (name) VALUES ('bricks');
INSERT INTO HARDWARE_CATEGORY (name) VALUES ('hammers');
INSERT INTO HARDWARE_CATEGORY (name) VALUES ('drillers');
INSERT INTO HARDWARE_CATEGORY (name) VALUES ('brushes');
INSERT INTO HARDWARE_CATEGORY (name) VALUES ('screwdrivers');